# Generated by Django 4.2.1 on 2023-05-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopFront', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='jishnu ramesh', max_length=100),
            preserve_default=False,
        ),
    ]
